# Generated by Django 4.2.7 on 2023-11-23 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_comment_author_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author_name',
            new_name='user',
        ),
    ]
