version: '3'

services:
  redis:
    image: redis
    restart: always
  django:
    build: .
    container_name: drf
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
  celery:
    restart: always
    build:
       context: .
    command: celery -A filmGallery worker -l info
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
      - django




